### ISSUE TITLE
样式部分描述有问题

### ISSUE THREAD

**Issue by yisibl** [s5s5/Code-snippets-of-s5s5#1]
1.禁止使用 \* 选择器

事实上单独的 \* 选择器性能影响不大。

2.尽量避免使用 ID 选择器，为了提升样式重用性以及与页面的耦合性

确定是页面唯一的元素应该是用ID，例如 `#header`，`#footer` 等。

**Comment by s5s5** [comment]
1、影响不大不等于没影响
2、一般情况都不怎么确定

**Comment by yisibl** [comment]
@s5s5 参见：https://github.com/yisibl/css-creating#selector
